added Modal to Portfolio Page
denysM789/crypto-app pull request #17
Opened 2022-08-12 09:08 UTC by denysM789

- general Modal added to Portfolio Page
- user-data not yet saved in Redux store
- CSS not yet at 100%

2022-08-12 19:47 UTC, yoloOnTheBattlefield requested changes

2022-08-12 19:47 UTC, yoloOnTheBattlefield commented on src/components/Portfolio/Modal/Modal.js
> +  useEffect(() => {}, [showCalendar]);
no need for this

2022-08-12 19:47 UTC, yoloOnTheBattlefield commented on src/components/Portfolio/Modal/Modal.js
> +  useEffect(() => {}, [showInput]);
no need for this

2022-08-12 19:47 UTC, yoloOnTheBattlefield commented on src/pages/Portfolio/Portfolio.js
> +  // }, [showModal]);
no need for this

2022-08-13 13:54 UTC, denysM789 commented on src/components/Portfolio/Modal/Modal.js
> +  useEffect(() => {}, [showCalendar]);
deleted the useEffect

2022-08-13 13:54 UTC, denysM789 commented on src/pages/Portfolio/Portfolio.js
> +  // }, [showModal]);
deleted the useEffect

2022-08-13 13:55 UTC, denysM789 commented on src/pages/Portfolio/Portfolio.js
> +  // }, [showModal]);
done

2022-08-13 15:39 UTC, yoloOnTheBattlefield approved these changes

2022-08-13 16:08 UTC, merged